### ISSUE TITLE
What is the sample search file for?

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/GitHub-Issue-Mining#39]
https://github.com/ponder-lab/GitHub-Issue-Mining/blob/b88a9604d3bc9b2b56d4a0fd651b8be352c150af/search_sample.json#L1

**Comment by y3pio** [comment]
That's just the sample response object of the search query API call. I stored the response as a static file for development purpose (so we don't waste our API quota).

**Comment by khatchad** [comment]
Cool thanks.
